version: "3.2"
# ----------------------------------------------------------------------------
# NETWORKS
# ----------------------------------------------------------------------------
networks:
  backend:
    driver: "bridge"
services:
  # ----------------------------------------------------------------------------
  # NGINX AND CERTBOT
  # Nginx and certbot for ssl termination
  # ----------------------------------------------------------------------------
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    depends_on:
      - redis
      - mysql
      - keycloak
    ports:
      - 127.0.0.1:81:80
      - 127.0.0.1:453:443
    networks: 
      - backend
    # volumes:
    #   - ./data/nginx/html:/usr/share/nginx/html
    #   - ./data/nginx:/etc/nginx/conf.d
  # ----------------------------------------------------------------------------
  # KEYCLOCK
  # Adding keycloack
  # ----------------------------------------------------------------------------
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: jboss/keycloak:6.0.1 
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8180:8080"
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. 
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "connectTimeout=30000"
    networks: 
      - backend
    volumes:
      - type: bind
        source: ./data/keycloak/themes/example/adminlte
        target: /opt/jboss/keycloak/themes/adminlte
  # ----------------------------------------------------------------------------
  # MYSQL
  # Uses mariadb instance
  # ----------------------------------------------------------------------------
  mysql:
    container_name: mariadb # Todo: Change to mysql when testing is complete
    hostname: mysql
    build: ./mariadb
    restart: unless-stopped
    ports:
      - 127.0.0.1:3406:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    networks: 
      - backend
    volumes:
      - mysql-volume:/var/lib/mysql
  # ----------------------------------------------------------------------------
  # REDIS
  # ----------------------------------------------------------------------------
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6000:6379
    networks: 
      - backend
    volumes:
      - redis-volume:/data
# ----------------------------------------------------------------------------
# VOLUMES
volumes:
  mysql-volume:
  nodered-volume:
  redis-volume:
# ----------------------------------------------------------------------------
